spring:
  datasource:
    # SQL url地址，myvuesql是数据库的名字
    url: jdbc:mysql://localhost:3306/myvuesql?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root    # SQL 账号
    password: root    # SQL 密码
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true  # jpa 打印SQL
    properties:
      hibernate:
        format_sql: true  # 格式化SQL
server:
  port: 8181    #设置端口